"""empty message

Revision ID: 478850928c03
Revises: 
Create Date: 2019-03-10 12:53:09.415818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478850928c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base', sa.String(length=5), nullable=False),
    sa.Column('to', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchangeratedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate_value', sa.Numeric(), nullable=False),
    sa.Column('exchangerate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchangerate_id'], ['exchangerate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_id'], ['exchangerate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.drop_table('trackrate')
    op.drop_table('exchangeratedata')
    op.drop_table('exchangerate')
    # ### end Alembic commands ###
